r"""
    This code was generated by
   ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
    |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
    |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \

    Twilio - Voice
    This is the public Twilio REST API.

    NOTE: This class is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
    Do not edit the class manually.
"""

from typing import Optional
from twilio.base.version import Version
from twilio.base.domain import Domain
from twilio.rest.voice.v1.archived_call import ArchivedCallList
from twilio.rest.voice.v1.byoc_trunk import ByocTrunkList
from twilio.rest.voice.v1.connection_policy import ConnectionPolicyList
from twilio.rest.voice.v1.dialing_permissions import DialingPermissionsList
from twilio.rest.voice.v1.ip_record import IpRecordList
from twilio.rest.voice.v1.source_ip_mapping import SourceIpMappingList


class V1(Version):

    def __init__(self, domain: Domain):
        """
        Initialize the V1 version of Voice

        :param domain: The Twilio.voice domain
        """
        super().__init__(domain, "v1")
        self._archived_calls: Optional[ArchivedCallList] = None
        self._byoc_trunks: Optional[ByocTrunkList] = None
        self._connection_policies: Optional[ConnectionPolicyList] = None
        self._dialing_permissions: Optional[DialingPermissionsList] = None
        self._ip_records: Optional[IpRecordList] = None
        self._source_ip_mappings: Optional[SourceIpMappingList] = None

    @property
    def archived_calls(self) -> ArchivedCallList:
        pass

    @property
    def byoc_trunks(self) -> ByocTrunkList:
        pass

    @property
    def connection_policies(self) -> ConnectionPolicyList:
        pass

    @property
    def dialing_permissions(self) -> DialingPermissionsList:
        pass

    @property
    def ip_records(self) -> IpRecordList:
        pass

    @property
    def source_ip_mappings(self) -> SourceIpMappingList:
        pass

    def __repr__(self) -> str:
        """
        Provide a friendly representation
        :returns: Machine friendly representation
        """
        return "<Twilio.Voice.V1>"
