r"""
    This code was generated by
   ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
    |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
    |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \

    Twilio - Numbers
    This is the public Twilio REST API.

    NOTE: This class is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
    Do not edit the class manually.
"""

from typing import Optional
from twilio.base.version import Version
from twilio.base.domain import Domain
from twilio.rest.numbers.v2.application import ApplicationList
from twilio.rest.numbers.v2.authorization_document import AuthorizationDocumentList
from twilio.rest.numbers.v2.bulk_hosted_number_order import BulkHostedNumberOrderList
from twilio.rest.numbers.v2.bundle_clone import BundleCloneList
from twilio.rest.numbers.v2.hosted_number_order import HostedNumberOrderList
from twilio.rest.numbers.v2.regulatory_compliance import RegulatoryComplianceList


class V2(Version):

    def __init__(self, domain: Domain):
        """
        Initialize the V2 version of Numbers

        :param domain: The Twilio.numbers domain
        """
        super().__init__(domain, "v2")
        self._applications: Optional[ApplicationList] = None
        self._authorization_documents: Optional[AuthorizationDocumentList] = None
        self._bulk_hosted_number_orders: Optional[BulkHostedNumberOrderList] = None
        self._bundle_clone: Optional[BundleCloneList] = None
        self._hosted_number_orders: Optional[HostedNumberOrderList] = None
        self._regulatory_compliance: Optional[RegulatoryComplianceList] = None

    @property
    def applications(self) -> ApplicationList:
        pass

    @property
    def authorization_documents(self) -> AuthorizationDocumentList:
        pass

    @property
    def bulk_hosted_number_orders(self) -> BulkHostedNumberOrderList:
        pass

    @property
    def bundle_clone(self) -> BundleCloneList:
        pass

    @property
    def hosted_number_orders(self) -> HostedNumberOrderList:
        pass

    @property
    def regulatory_compliance(self) -> RegulatoryComplianceList:
        pass

    def __repr__(self) -> str:
        """
        Provide a friendly representation
        :returns: Machine friendly representation
        """
        return "<Twilio.Numbers.V2>"
