r"""
    This code was generated by
   ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
    |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
    |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \

    Twilio - Sync
    This is the public Twilio REST API.

    NOTE: This class is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
    Do not edit the class manually.
"""

from typing import Any, Dict, List, Optional, Union, Iterator, AsyncIterator
from twilio.base import serialize, values
from twilio.base.api_response import ApiResponse
from twilio.base.instance_context import InstanceContext
from twilio.base.instance_resource import InstanceResource
from twilio.base.list_resource import ListResource
from twilio.base.version import Version
from twilio.base.page import Page


class SyncMapPermissionInstance(InstanceResource):
    """
    :ivar account_sid: The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Sync Map Permission resource.
    :ivar service_sid: The SID of the [Sync Service](https://www.twilio.com/docs/sync/api/service) the resource is associated with.
    :ivar map_sid: The SID of the Sync Map to which the Permission applies.
    :ivar identity: The application-defined string that uniquely identifies the resource's User within the Service to an FPA token.
    :ivar read: Whether the identity can read the Sync Map and its Items.
    :ivar write: Whether the identity can create, update, and delete Items in the Sync Map.
    :ivar manage: Whether the identity can delete the Sync Map.
    :ivar url: The absolute URL of the Sync Map Permission resource.
    """

    def __init__(
        self,
        version: Version,
        payload: Dict[str, Any],
        service_sid: str,
        map_sid: str,
        identity: Optional[str] = None,
    ):
        super().__init__(version)

        self.account_sid: Optional[str] = payload.get("account_sid")
        self.service_sid: Optional[str] = payload.get("service_sid")
        self.map_sid: Optional[str] = payload.get("map_sid")
        self.identity: Optional[str] = payload.get("identity")
        self.read: Optional[bool] = payload.get("read")
        self.write: Optional[bool] = payload.get("write")
        self.manage: Optional[bool] = payload.get("manage")
        self.url: Optional[str] = payload.get("url")

        self._solution = {
            "service_sid": service_sid,
            "map_sid": map_sid,
            "identity": identity or self.identity,
        }
        self._context: Optional[SyncMapPermissionContext] = None

    @property
    def _proxy(self) -> "SyncMapPermissionContext":
        """
        Generate an instance context for the instance, the context is capable of
        performing various actions. All instance actions are proxied to the context

        :returns: SyncMapPermissionContext for this SyncMapPermissionInstance
        """
        pass

    def delete(self) -> bool:
        """
        Deletes the SyncMapPermissionInstance


        :returns: True if delete succeeds, False otherwise
        """
        pass

    async def delete_async(self) -> bool:
        """
        Asynchronous coroutine that deletes the SyncMapPermissionInstance


        :returns: True if delete succeeds, False otherwise
        """
        pass

    def delete_with_http_info(self) -> ApiResponse:
        """
        Deletes the SyncMapPermissionInstance with HTTP info


        :returns: ApiResponse with success boolean, status code, and headers
        """
        pass

    async def delete_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronous coroutine that deletes the SyncMapPermissionInstance with HTTP info


        :returns: ApiResponse with success boolean, status code, and headers
        """
        pass

    def fetch(self) -> "SyncMapPermissionInstance":
        """
        Fetch the SyncMapPermissionInstance


        :returns: The fetched SyncMapPermissionInstance
        """
        pass

    async def fetch_async(self) -> "SyncMapPermissionInstance":
        """
        Asynchronous coroutine to fetch the SyncMapPermissionInstance


        :returns: The fetched SyncMapPermissionInstance
        """
        pass

    def fetch_with_http_info(self) -> ApiResponse:
        """
        Fetch the SyncMapPermissionInstance with HTTP info


        :returns: ApiResponse with instance, status code, and headers
        """
        pass

    async def fetch_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronous coroutine to fetch the SyncMapPermissionInstance with HTTP info


        :returns: ApiResponse with instance, status code, and headers
        """
        pass

    def update(
        self, read: bool, write: bool, manage: bool
    ) -> "SyncMapPermissionInstance":
        """
        Update the SyncMapPermissionInstance

        :param read: Whether the identity can read the Sync Map and its Items. Default value is `false`.
        :param write: Whether the identity can create, update, and delete Items in the Sync Map. Default value is `false`.
        :param manage: Whether the identity can delete the Sync Map. Default value is `false`.

        :returns: The updated SyncMapPermissionInstance
        """
        pass

    async def update_async(
        self, read: bool, write: bool, manage: bool
    ) -> "SyncMapPermissionInstance":
        """
        Asynchronous coroutine to update the SyncMapPermissionInstance

        :param read: Whether the identity can read the Sync Map and its Items. Default value is `false`.
        :param write: Whether the identity can create, update, and delete Items in the Sync Map. Default value is `false`.
        :param manage: Whether the identity can delete the Sync Map. Default value is `false`.

        :returns: The updated SyncMapPermissionInstance
        """
        pass

    def update_with_http_info(
        self, read: bool, write: bool, manage: bool
    ) -> ApiResponse:
        """
        Update the SyncMapPermissionInstance with HTTP info

        :param read: Whether the identity can read the Sync Map and its Items. Default value is `false`.
        :param write: Whether the identity can create, update, and delete Items in the Sync Map. Default value is `false`.
        :param manage: Whether the identity can delete the Sync Map. Default value is `false`.

        :returns: ApiResponse with instance, status code, and headers
        """
        pass

    async def update_with_http_info_async(
        self, read: bool, write: bool, manage: bool
    ) -> ApiResponse:
        """
        Asynchronous coroutine to update the SyncMapPermissionInstance with HTTP info

        :param read: Whether the identity can read the Sync Map and its Items. Default value is `false`.
        :param write: Whether the identity can create, update, and delete Items in the Sync Map. Default value is `false`.
        :param manage: Whether the identity can delete the Sync Map. Default value is `false`.

        :returns: ApiResponse with instance, status code, and headers
        """
        pass

    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        context = " ".join("{}={}".format(k, v) for k, v in self._solution.items())
        return "<Twilio.Sync.V1.SyncMapPermissionInstance {}>".format(context)


class SyncMapPermissionContext(InstanceContext):

    def __init__(self, version: Version, service_sid: str, map_sid: str, identity: str):
        """
        Initialize the SyncMapPermissionContext

        :param version: Version that contains the resource
        :param service_sid: The SID of the [Sync Service](https://www.twilio.com/docs/sync/api/service) with the Sync Map Permission resource to update. Can be the Service's `sid` value or `default`.
        :param map_sid: The SID of the Sync Map with the Sync Map Permission resource to update. Can be the Sync Map resource's `sid` or its `unique_name`.
        :param identity: The application-defined string that uniquely identifies the User's Sync Map Permission resource to update.
        """
        super().__init__(version)

        # Path Solution
        self._solution = {
            "service_sid": service_sid,
            "map_sid": map_sid,
            "identity": identity,
        }
        self._uri = (
            "/Services/{service_sid}/Maps/{map_sid}/Permissions/{identity}".format(
                **self._solution
            )
        )

    def _delete(self) -> tuple:
        """
        Internal helper for delete operation

        Returns:
            tuple: (success_boolean, status_code, headers)
        """
        pass

    def delete(self) -> bool:
        """
        Deletes the SyncMapPermissionInstance


        :returns: True if delete succeeds, False otherwise
        """
        pass

    def delete_with_http_info(self) -> ApiResponse:
        """
        Deletes the SyncMapPermissionInstance and return response metadata


        :returns: ApiResponse with success boolean, status code, and headers
        """
        pass

    async def _delete_async(self) -> tuple:
        """
        Internal async helper for delete operation

        Returns:
            tuple: (success_boolean, status_code, headers)
        """
        pass

    async def delete_async(self) -> bool:
        """
        Asynchronous coroutine that deletes the SyncMapPermissionInstance


        :returns: True if delete succeeds, False otherwise
        """
        pass

    async def delete_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronous coroutine that deletes the SyncMapPermissionInstance and return response metadata


        :returns: ApiResponse with success boolean, status code, and headers
        """
        pass

    def _fetch(self) -> tuple:
        """
        Internal helper for fetch operation

        Returns:
            tuple: (payload, status_code, headers)
        """
        pass

    def fetch(self) -> SyncMapPermissionInstance:
        """
        Fetch the SyncMapPermissionInstance


        :returns: The fetched SyncMapPermissionInstance
        """
        pass

    def fetch_with_http_info(self) -> ApiResponse:
        """
        Fetch the SyncMapPermissionInstance and return response metadata


        :returns: ApiResponse with instance, status code, and headers
        """
        pass

    async def _fetch_async(self) -> tuple:
        """
        Internal async helper for fetch operation

        Returns:
            tuple: (payload, status_code, headers)
        """
        pass

    async def fetch_async(self) -> SyncMapPermissionInstance:
        """
        Asynchronous coroutine to fetch the SyncMapPermissionInstance


        :returns: The fetched SyncMapPermissionInstance
        """
        pass

    async def fetch_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronous coroutine to fetch the SyncMapPermissionInstance and return response metadata


        :returns: ApiResponse with instance, status code, and headers
        """
        pass

    def _update(self, read: bool, write: bool, manage: bool) -> tuple:
        """
        Internal helper for update operation

        Returns:
            tuple: (payload, status_code, headers)
        """
        pass

    def update(
        self, read: bool, write: bool, manage: bool
    ) -> SyncMapPermissionInstance:
        """
        Update the SyncMapPermissionInstance

        :param read: Whether the identity can read the Sync Map and its Items. Default value is `false`.
        :param write: Whether the identity can create, update, and delete Items in the Sync Map. Default value is `false`.
        :param manage: Whether the identity can delete the Sync Map. Default value is `false`.

        :returns: The updated SyncMapPermissionInstance
        """
        pass

    def update_with_http_info(
        self, read: bool, write: bool, manage: bool
    ) -> ApiResponse:
        """
        Update the SyncMapPermissionInstance and return response metadata

        :param read: Whether the identity can read the Sync Map and its Items. Default value is `false`.
        :param write: Whether the identity can create, update, and delete Items in the Sync Map. Default value is `false`.
        :param manage: Whether the identity can delete the Sync Map. Default value is `false`.

        :returns: ApiResponse with instance, status code, and headers
        """
        pass

    async def _update_async(self, read: bool, write: bool, manage: bool) -> tuple:
        """
        Internal async helper for update operation

        Returns:
            tuple: (payload, status_code, headers)
        """
        pass

    async def update_async(
        self, read: bool, write: bool, manage: bool
    ) -> SyncMapPermissionInstance:
        """
        Asynchronous coroutine to update the SyncMapPermissionInstance

        :param read: Whether the identity can read the Sync Map and its Items. Default value is `false`.
        :param write: Whether the identity can create, update, and delete Items in the Sync Map. Default value is `false`.
        :param manage: Whether the identity can delete the Sync Map. Default value is `false`.

        :returns: The updated SyncMapPermissionInstance
        """
        pass

    async def update_with_http_info_async(
        self, read: bool, write: bool, manage: bool
    ) -> ApiResponse:
        """
        Asynchronous coroutine to update the SyncMapPermissionInstance and return response metadata

        :param read: Whether the identity can read the Sync Map and its Items. Default value is `false`.
        :param write: Whether the identity can create, update, and delete Items in the Sync Map. Default value is `false`.
        :param manage: Whether the identity can delete the Sync Map. Default value is `false`.

        :returns: ApiResponse with instance, status code, and headers
        """
        pass

    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        context = " ".join("{}={}".format(k, v) for k, v in self._solution.items())
        return "<Twilio.Sync.V1.SyncMapPermissionContext {}>".format(context)


class SyncMapPermissionPage(Page):

    def get_instance(self, payload: Dict[str, Any]) -> SyncMapPermissionInstance:
        """
        Build an instance of SyncMapPermissionInstance

        :param payload: Payload response from the API
        """
        pass

    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        return "<Twilio.Sync.V1.SyncMapPermissionPage>"


class SyncMapPermissionList(ListResource):

    def __init__(self, version: Version, service_sid: str, map_sid: str):
        """
        Initialize the SyncMapPermissionList

        :param version: Version that contains the resource
        :param service_sid: The SID of the [Sync Service](https://www.twilio.com/docs/sync/api/service) with the Sync Map Permission resources to read. Can be the Service's `sid` value or `default`.
        :param map_sid: The SID of the Sync Map with the Permission resources to read. Can be the Sync Map resource's `sid` or its `unique_name`.

        """
        super().__init__(version)

        # Path Solution
        self._solution = {
            "service_sid": service_sid,
            "map_sid": map_sid,
        }
        self._uri = "/Services/{service_sid}/Maps/{map_sid}/Permissions".format(
            **self._solution
        )

    def stream(
        self,
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> Iterator[SyncMapPermissionInstance]:
        """
        Streams SyncMapPermissionInstance records from the API as a generator stream.
        This operation lazily loads records as efficiently as possible until the limit
        is reached.
        The results are returned as a generator, so this operation is memory efficient.

        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: Generator that will yield up to limit results
        """
        pass

    async def stream_async(
        self,
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> AsyncIterator[SyncMapPermissionInstance]:
        """
        Asynchronously streams SyncMapPermissionInstance records from the API as a generator stream.
        This operation lazily loads records as efficiently as possible until the limit
        is reached.
        The results are returned as a generator, so this operation is memory efficient.

        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: Generator that will yield up to limit results
        """
        pass

    def stream_with_http_info(
        self,
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> tuple:
        """
        Streams SyncMapPermissionInstance and returns headers from first page


        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: tuple of (generator, status_code, headers) where generator yields instances
        """
        pass

    async def stream_with_http_info_async(
        self,
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> tuple:
        """
        Asynchronously streams SyncMapPermissionInstance and returns headers from first page


        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: tuple of (generator, status_code, headers) where generator yields instances
        """
        pass

    def list(
        self,
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> List[SyncMapPermissionInstance]:
        """
        Lists SyncMapPermissionInstance records from the API as a list.
        Unlike stream(), this operation is eager and will load `limit` records into
        memory before returning.

        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: list that will contain up to limit results
        """
        pass

    async def list_async(
        self,
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> List[SyncMapPermissionInstance]:
        """
        Asynchronously lists SyncMapPermissionInstance records from the API as a list.
        Unlike stream(), this operation is eager and will load `limit` records into
        memory before returning.

        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: list that will contain up to limit results
        """
        pass

    def list_with_http_info(
        self,
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Lists SyncMapPermissionInstance and returns headers from first page


        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        pass

    async def list_with_http_info_async(
        self,
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Asynchronously lists SyncMapPermissionInstance and returns headers from first page


        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        pass

    def page(
        self,
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> SyncMapPermissionPage:
        """
        Retrieve a single page of SyncMapPermissionInstance records from the API.
        Request is executed immediately

        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of SyncMapPermissionInstance
        """
        pass

    async def page_async(
        self,
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> SyncMapPermissionPage:
        """
        Asynchronously retrieve a single page of SyncMapPermissionInstance records from the API.
        Request is executed immediately

        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of SyncMapPermissionInstance
        """
        pass

    def page_with_http_info(
        self,
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Retrieve a single page with response metadata


        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with SyncMapPermissionPage, status code, and headers
        """
        pass

    async def page_with_http_info_async(
        self,
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Asynchronously retrieve a single page with response metadata


        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with SyncMapPermissionPage, status code, and headers
        """
        pass

    def get_page(self, target_url: str) -> SyncMapPermissionPage:
        """
        Retrieve a specific page of SyncMapPermissionInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of SyncMapPermissionInstance
        """
        pass

    async def get_page_async(self, target_url: str) -> SyncMapPermissionPage:
        """
        Asynchronously retrieve a specific page of SyncMapPermissionInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of SyncMapPermissionInstance
        """
        pass

    def get(self, identity: str) -> SyncMapPermissionContext:
        """
        Constructs a SyncMapPermissionContext

        :param identity: The application-defined string that uniquely identifies the User's Sync Map Permission resource to update.
        """
        pass

    def __call__(self, identity: str) -> SyncMapPermissionContext:
        """
        Constructs a SyncMapPermissionContext

        :param identity: The application-defined string that uniquely identifies the User's Sync Map Permission resource to update.
        """
        return SyncMapPermissionContext(
            self._version,
            service_sid=self._solution["service_sid"],
            map_sid=self._solution["map_sid"],
            identity=identity,
        )

    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        return "<Twilio.Sync.V1.SyncMapPermissionList>"
