r"""
    This code was generated by
   ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
    |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
    |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \

    Twilio - Voice
    This is the public Twilio REST API.

    NOTE: This class is auto generated by OpenAPI Generator.
    https://openapi-generator.tech
    Do not edit the class manually.
"""

from datetime import datetime
from typing import Any, Dict, List, Optional, Union, Iterator, AsyncIterator
from twilio.base import deserialize, serialize, values
from twilio.base.api_response import ApiResponse
from twilio.base.instance_context import InstanceContext
from twilio.base.instance_resource import InstanceResource
from twilio.base.list_resource import ListResource
from twilio.base.version import Version
from twilio.base.page import Page


class ConnectionPolicyTargetInstance(InstanceResource):
    """
    :ivar account_sid: The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Target resource.
    :ivar connection_policy_sid: The SID of the Connection Policy that owns the Target.
    :ivar sid: The unique string that we created to identify the Target resource.
    :ivar friendly_name: The string that you assigned to describe the resource.
    :ivar target: The SIP address you want Twilio to route your calls to. This must be a `sip:` schema. `sips` is NOT supported.
    :ivar priority: The relative importance of the target. Can be an integer from 0 to 65535, inclusive, and the default is 10. The lowest number represents the most important target.
    :ivar weight: The value that determines the relative share of the load the Target should receive compared to other Targets with the same priority. Can be an integer from 1 to 65535, inclusive, and the default is 10. Targets with higher values receive more load than those with lower ones with the same priority.
    :ivar enabled: Whether the target is enabled. The default is `true`.
    :ivar date_created: The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
    :ivar date_updated: The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
    :ivar url: The absolute URL of the resource.
    """

    def __init__(
        self,
        version: Version,
        payload: Dict[str, Any],
        connection_policy_sid: str,
        sid: Optional[str] = None,
    ):
        super().__init__(version)

        self.account_sid: Optional[str] = payload.get("account_sid")
        self.connection_policy_sid: Optional[str] = payload.get("connection_policy_sid")
        self.sid: Optional[str] = payload.get("sid")
        self.friendly_name: Optional[str] = payload.get("friendly_name")
        self.target: Optional[str] = payload.get("target")
        self.priority: Optional[int] = deserialize.integer(payload.get("priority"))
        self.weight: Optional[int] = deserialize.integer(payload.get("weight"))
        self.enabled: Optional[bool] = payload.get("enabled")
        self.date_created: Optional[datetime] = deserialize.iso8601_datetime(
            payload.get("date_created")
        )
        self.date_updated: Optional[datetime] = deserialize.iso8601_datetime(
            payload.get("date_updated")
        )
        self.url: Optional[str] = payload.get("url")

        self._solution = {
            "connection_policy_sid": connection_policy_sid,
            "sid": sid or self.sid,
        }
        self._context: Optional[ConnectionPolicyTargetContext] = None

    @property
    def _proxy(self) -> "ConnectionPolicyTargetContext":
        """
        Generate an instance context for the instance, the context is capable of
        performing various actions. All instance actions are proxied to the context

        :returns: ConnectionPolicyTargetContext for this ConnectionPolicyTargetInstance
        """
        pass

    def delete(self) -> bool:
        """
        Deletes the ConnectionPolicyTargetInstance


        :returns: True if delete succeeds, False otherwise
        """
        pass

    async def delete_async(self) -> bool:
        """
        Asynchronous coroutine that deletes the ConnectionPolicyTargetInstance


        :returns: True if delete succeeds, False otherwise
        """
        pass

    def delete_with_http_info(self) -> ApiResponse:
        """
        Deletes the ConnectionPolicyTargetInstance with HTTP info


        :returns: ApiResponse with success boolean, status code, and headers
        """
        pass

    async def delete_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronous coroutine that deletes the ConnectionPolicyTargetInstance with HTTP info


        :returns: ApiResponse with success boolean, status code, and headers
        """
        pass

    def fetch(self) -> "ConnectionPolicyTargetInstance":
        """
        Fetch the ConnectionPolicyTargetInstance


        :returns: The fetched ConnectionPolicyTargetInstance
        """
        pass

    async def fetch_async(self) -> "ConnectionPolicyTargetInstance":
        """
        Asynchronous coroutine to fetch the ConnectionPolicyTargetInstance


        :returns: The fetched ConnectionPolicyTargetInstance
        """
        pass

    def fetch_with_http_info(self) -> ApiResponse:
        """
        Fetch the ConnectionPolicyTargetInstance with HTTP info


        :returns: ApiResponse with instance, status code, and headers
        """
        pass

    async def fetch_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronous coroutine to fetch the ConnectionPolicyTargetInstance with HTTP info


        :returns: ApiResponse with instance, status code, and headers
        """
        pass

    def update(
        self,
        friendly_name: Union[str, object] = values.unset,
        target: Union[str, object] = values.unset,
        priority: Union[int, object] = values.unset,
        weight: Union[int, object] = values.unset,
        enabled: Union[bool, object] = values.unset,
    ) -> "ConnectionPolicyTargetInstance":
        """
        Update the ConnectionPolicyTargetInstance

        :param friendly_name: A descriptive string that you create to describe the resource. It is not unique and can be up to 255 characters long.
        :param target: The SIP address you want Twilio to route your calls to. This must be a `sip:` schema. `sips` is NOT supported.
        :param priority: The relative importance of the target. Can be an integer from 0 to 65535, inclusive. The lowest number represents the most important target.
        :param weight: The value that determines the relative share of the load the Target should receive compared to other Targets with the same priority. Can be an integer from 1 to 65535, inclusive. Targets with higher values receive more load than those with lower ones with the same priority.
        :param enabled: Whether the Target is enabled.

        :returns: The updated ConnectionPolicyTargetInstance
        """
        pass

    async def update_async(
        self,
        friendly_name: Union[str, object] = values.unset,
        target: Union[str, object] = values.unset,
        priority: Union[int, object] = values.unset,
        weight: Union[int, object] = values.unset,
        enabled: Union[bool, object] = values.unset,
    ) -> "ConnectionPolicyTargetInstance":
        """
        Asynchronous coroutine to update the ConnectionPolicyTargetInstance

        :param friendly_name: A descriptive string that you create to describe the resource. It is not unique and can be up to 255 characters long.
        :param target: The SIP address you want Twilio to route your calls to. This must be a `sip:` schema. `sips` is NOT supported.
        :param priority: The relative importance of the target. Can be an integer from 0 to 65535, inclusive. The lowest number represents the most important target.
        :param weight: The value that determines the relative share of the load the Target should receive compared to other Targets with the same priority. Can be an integer from 1 to 65535, inclusive. Targets with higher values receive more load than those with lower ones with the same priority.
        :param enabled: Whether the Target is enabled.

        :returns: The updated ConnectionPolicyTargetInstance
        """
        pass

    def update_with_http_info(
        self,
        friendly_name: Union[str, object] = values.unset,
        target: Union[str, object] = values.unset,
        priority: Union[int, object] = values.unset,
        weight: Union[int, object] = values.unset,
        enabled: Union[bool, object] = values.unset,
    ) -> ApiResponse:
        """
        Update the ConnectionPolicyTargetInstance with HTTP info

        :param friendly_name: A descriptive string that you create to describe the resource. It is not unique and can be up to 255 characters long.
        :param target: The SIP address you want Twilio to route your calls to. This must be a `sip:` schema. `sips` is NOT supported.
        :param priority: The relative importance of the target. Can be an integer from 0 to 65535, inclusive. The lowest number represents the most important target.
        :param weight: The value that determines the relative share of the load the Target should receive compared to other Targets with the same priority. Can be an integer from 1 to 65535, inclusive. Targets with higher values receive more load than those with lower ones with the same priority.
        :param enabled: Whether the Target is enabled.

        :returns: ApiResponse with instance, status code, and headers
        """
        pass

    async def update_with_http_info_async(
        self,
        friendly_name: Union[str, object] = values.unset,
        target: Union[str, object] = values.unset,
        priority: Union[int, object] = values.unset,
        weight: Union[int, object] = values.unset,
        enabled: Union[bool, object] = values.unset,
    ) -> ApiResponse:
        """
        Asynchronous coroutine to update the ConnectionPolicyTargetInstance with HTTP info

        :param friendly_name: A descriptive string that you create to describe the resource. It is not unique and can be up to 255 characters long.
        :param target: The SIP address you want Twilio to route your calls to. This must be a `sip:` schema. `sips` is NOT supported.
        :param priority: The relative importance of the target. Can be an integer from 0 to 65535, inclusive. The lowest number represents the most important target.
        :param weight: The value that determines the relative share of the load the Target should receive compared to other Targets with the same priority. Can be an integer from 1 to 65535, inclusive. Targets with higher values receive more load than those with lower ones with the same priority.
        :param enabled: Whether the Target is enabled.

        :returns: ApiResponse with instance, status code, and headers
        """
        pass

    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        context = " ".join("{}={}".format(k, v) for k, v in self._solution.items())
        return "<Twilio.Voice.V1.ConnectionPolicyTargetInstance {}>".format(context)


class ConnectionPolicyTargetContext(InstanceContext):

    def __init__(self, version: Version, connection_policy_sid: str, sid: str):
        """
        Initialize the ConnectionPolicyTargetContext

        :param version: Version that contains the resource
        :param connection_policy_sid: The SID of the Connection Policy that owns the Target.
        :param sid: The unique string that we created to identify the Target resource to update.
        """
        super().__init__(version)

        # Path Solution
        self._solution = {
            "connection_policy_sid": connection_policy_sid,
            "sid": sid,
        }
        self._uri = "/ConnectionPolicies/{connection_policy_sid}/Targets/{sid}".format(
            **self._solution
        )

    def _delete(self) -> tuple:
        """
        Internal helper for delete operation

        Returns:
            tuple: (success_boolean, status_code, headers)
        """
        pass

    def delete(self) -> bool:
        """
        Deletes the ConnectionPolicyTargetInstance


        :returns: True if delete succeeds, False otherwise
        """
        pass

    def delete_with_http_info(self) -> ApiResponse:
        """
        Deletes the ConnectionPolicyTargetInstance and return response metadata


        :returns: ApiResponse with success boolean, status code, and headers
        """
        pass

    async def _delete_async(self) -> tuple:
        """
        Internal async helper for delete operation

        Returns:
            tuple: (success_boolean, status_code, headers)
        """
        pass

    async def delete_async(self) -> bool:
        """
        Asynchronous coroutine that deletes the ConnectionPolicyTargetInstance


        :returns: True if delete succeeds, False otherwise
        """
        pass

    async def delete_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronous coroutine that deletes the ConnectionPolicyTargetInstance and return response metadata


        :returns: ApiResponse with success boolean, status code, and headers
        """
        pass

    def _fetch(self) -> tuple:
        """
        Internal helper for fetch operation

        Returns:
            tuple: (payload, status_code, headers)
        """
        pass

    def fetch(self) -> ConnectionPolicyTargetInstance:
        """
        Fetch the ConnectionPolicyTargetInstance


        :returns: The fetched ConnectionPolicyTargetInstance
        """
        pass

    def fetch_with_http_info(self) -> ApiResponse:
        """
        Fetch the ConnectionPolicyTargetInstance and return response metadata


        :returns: ApiResponse with instance, status code, and headers
        """
        pass

    async def _fetch_async(self) -> tuple:
        """
        Internal async helper for fetch operation

        Returns:
            tuple: (payload, status_code, headers)
        """
        pass

    async def fetch_async(self) -> ConnectionPolicyTargetInstance:
        """
        Asynchronous coroutine to fetch the ConnectionPolicyTargetInstance


        :returns: The fetched ConnectionPolicyTargetInstance
        """
        pass

    async def fetch_with_http_info_async(self) -> ApiResponse:
        """
        Asynchronous coroutine to fetch the ConnectionPolicyTargetInstance and return response metadata


        :returns: ApiResponse with instance, status code, and headers
        """
        pass

    def _update(
        self,
        friendly_name: Union[str, object] = values.unset,
        target: Union[str, object] = values.unset,
        priority: Union[int, object] = values.unset,
        weight: Union[int, object] = values.unset,
        enabled: Union[bool, object] = values.unset,
    ) -> tuple:
        """
        Internal helper for update operation

        Returns:
            tuple: (payload, status_code, headers)
        """
        pass

    def update(
        self,
        friendly_name: Union[str, object] = values.unset,
        target: Union[str, object] = values.unset,
        priority: Union[int, object] = values.unset,
        weight: Union[int, object] = values.unset,
        enabled: Union[bool, object] = values.unset,
    ) -> ConnectionPolicyTargetInstance:
        """
        Update the ConnectionPolicyTargetInstance

        :param friendly_name: A descriptive string that you create to describe the resource. It is not unique and can be up to 255 characters long.
        :param target: The SIP address you want Twilio to route your calls to. This must be a `sip:` schema. `sips` is NOT supported.
        :param priority: The relative importance of the target. Can be an integer from 0 to 65535, inclusive. The lowest number represents the most important target.
        :param weight: The value that determines the relative share of the load the Target should receive compared to other Targets with the same priority. Can be an integer from 1 to 65535, inclusive. Targets with higher values receive more load than those with lower ones with the same priority.
        :param enabled: Whether the Target is enabled.

        :returns: The updated ConnectionPolicyTargetInstance
        """
        pass

    def update_with_http_info(
        self,
        friendly_name: Union[str, object] = values.unset,
        target: Union[str, object] = values.unset,
        priority: Union[int, object] = values.unset,
        weight: Union[int, object] = values.unset,
        enabled: Union[bool, object] = values.unset,
    ) -> ApiResponse:
        """
        Update the ConnectionPolicyTargetInstance and return response metadata

        :param friendly_name: A descriptive string that you create to describe the resource. It is not unique and can be up to 255 characters long.
        :param target: The SIP address you want Twilio to route your calls to. This must be a `sip:` schema. `sips` is NOT supported.
        :param priority: The relative importance of the target. Can be an integer from 0 to 65535, inclusive. The lowest number represents the most important target.
        :param weight: The value that determines the relative share of the load the Target should receive compared to other Targets with the same priority. Can be an integer from 1 to 65535, inclusive. Targets with higher values receive more load than those with lower ones with the same priority.
        :param enabled: Whether the Target is enabled.

        :returns: ApiResponse with instance, status code, and headers
        """
        pass

    async def _update_async(
        self,
        friendly_name: Union[str, object] = values.unset,
        target: Union[str, object] = values.unset,
        priority: Union[int, object] = values.unset,
        weight: Union[int, object] = values.unset,
        enabled: Union[bool, object] = values.unset,
    ) -> tuple:
        """
        Internal async helper for update operation

        Returns:
            tuple: (payload, status_code, headers)
        """
        pass

    async def update_async(
        self,
        friendly_name: Union[str, object] = values.unset,
        target: Union[str, object] = values.unset,
        priority: Union[int, object] = values.unset,
        weight: Union[int, object] = values.unset,
        enabled: Union[bool, object] = values.unset,
    ) -> ConnectionPolicyTargetInstance:
        """
        Asynchronous coroutine to update the ConnectionPolicyTargetInstance

        :param friendly_name: A descriptive string that you create to describe the resource. It is not unique and can be up to 255 characters long.
        :param target: The SIP address you want Twilio to route your calls to. This must be a `sip:` schema. `sips` is NOT supported.
        :param priority: The relative importance of the target. Can be an integer from 0 to 65535, inclusive. The lowest number represents the most important target.
        :param weight: The value that determines the relative share of the load the Target should receive compared to other Targets with the same priority. Can be an integer from 1 to 65535, inclusive. Targets with higher values receive more load than those with lower ones with the same priority.
        :param enabled: Whether the Target is enabled.

        :returns: The updated ConnectionPolicyTargetInstance
        """
        pass

    async def update_with_http_info_async(
        self,
        friendly_name: Union[str, object] = values.unset,
        target: Union[str, object] = values.unset,
        priority: Union[int, object] = values.unset,
        weight: Union[int, object] = values.unset,
        enabled: Union[bool, object] = values.unset,
    ) -> ApiResponse:
        """
        Asynchronous coroutine to update the ConnectionPolicyTargetInstance and return response metadata

        :param friendly_name: A descriptive string that you create to describe the resource. It is not unique and can be up to 255 characters long.
        :param target: The SIP address you want Twilio to route your calls to. This must be a `sip:` schema. `sips` is NOT supported.
        :param priority: The relative importance of the target. Can be an integer from 0 to 65535, inclusive. The lowest number represents the most important target.
        :param weight: The value that determines the relative share of the load the Target should receive compared to other Targets with the same priority. Can be an integer from 1 to 65535, inclusive. Targets with higher values receive more load than those with lower ones with the same priority.
        :param enabled: Whether the Target is enabled.

        :returns: ApiResponse with instance, status code, and headers
        """
        pass

    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        context = " ".join("{}={}".format(k, v) for k, v in self._solution.items())
        return "<Twilio.Voice.V1.ConnectionPolicyTargetContext {}>".format(context)


class ConnectionPolicyTargetPage(Page):

    def get_instance(self, payload: Dict[str, Any]) -> ConnectionPolicyTargetInstance:
        """
        Build an instance of ConnectionPolicyTargetInstance

        :param payload: Payload response from the API
        """
        pass

    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        return "<Twilio.Voice.V1.ConnectionPolicyTargetPage>"


class ConnectionPolicyTargetList(ListResource):

    def __init__(self, version: Version, connection_policy_sid: str):
        """
        Initialize the ConnectionPolicyTargetList

        :param version: Version that contains the resource
        :param connection_policy_sid: The SID of the Connection Policy from which to read the Targets.

        """
        super().__init__(version)

        # Path Solution
        self._solution = {
            "connection_policy_sid": connection_policy_sid,
        }
        self._uri = "/ConnectionPolicies/{connection_policy_sid}/Targets".format(
            **self._solution
        )

    def _create(
        self,
        target: str,
        friendly_name: Union[str, object] = values.unset,
        priority: Union[int, object] = values.unset,
        weight: Union[int, object] = values.unset,
        enabled: Union[bool, object] = values.unset,
    ) -> tuple:
        """
        Internal helper for create operation

        Returns:
            tuple: (payload, status_code, headers)
        """
        pass

    def create(
        self,
        target: str,
        friendly_name: Union[str, object] = values.unset,
        priority: Union[int, object] = values.unset,
        weight: Union[int, object] = values.unset,
        enabled: Union[bool, object] = values.unset,
    ) -> ConnectionPolicyTargetInstance:
        """
        Create the ConnectionPolicyTargetInstance

        :param target: The SIP address you want Twilio to route your calls to. This must be a `sip:` schema. `sips` is NOT supported.
        :param friendly_name: A descriptive string that you create to describe the resource. It is not unique and can be up to 255 characters long.
        :param priority: The relative importance of the target. Can be an integer from 0 to 65535, inclusive, and the default is 10. The lowest number represents the most important target.
        :param weight: The value that determines the relative share of the load the Target should receive compared to other Targets with the same priority. Can be an integer from 1 to 65535, inclusive, and the default is 10. Targets with higher values receive more load than those with lower ones with the same priority.
        :param enabled: Whether the Target is enabled. The default is `true`.

        :returns: The created ConnectionPolicyTargetInstance
        """
        pass

    def create_with_http_info(
        self,
        target: str,
        friendly_name: Union[str, object] = values.unset,
        priority: Union[int, object] = values.unset,
        weight: Union[int, object] = values.unset,
        enabled: Union[bool, object] = values.unset,
    ) -> ApiResponse:
        """
        Create the ConnectionPolicyTargetInstance and return response metadata

        :param target: The SIP address you want Twilio to route your calls to. This must be a `sip:` schema. `sips` is NOT supported.
        :param friendly_name: A descriptive string that you create to describe the resource. It is not unique and can be up to 255 characters long.
        :param priority: The relative importance of the target. Can be an integer from 0 to 65535, inclusive, and the default is 10. The lowest number represents the most important target.
        :param weight: The value that determines the relative share of the load the Target should receive compared to other Targets with the same priority. Can be an integer from 1 to 65535, inclusive, and the default is 10. Targets with higher values receive more load than those with lower ones with the same priority.
        :param enabled: Whether the Target is enabled. The default is `true`.

        :returns: ApiResponse with instance, status code, and headers
        """
        pass

    async def _create_async(
        self,
        target: str,
        friendly_name: Union[str, object] = values.unset,
        priority: Union[int, object] = values.unset,
        weight: Union[int, object] = values.unset,
        enabled: Union[bool, object] = values.unset,
    ) -> tuple:
        """
        Internal async helper for create operation

        Returns:
            tuple: (payload, status_code, headers)
        """
        pass

    async def create_async(
        self,
        target: str,
        friendly_name: Union[str, object] = values.unset,
        priority: Union[int, object] = values.unset,
        weight: Union[int, object] = values.unset,
        enabled: Union[bool, object] = values.unset,
    ) -> ConnectionPolicyTargetInstance:
        """
        Asynchronously create the ConnectionPolicyTargetInstance

        :param target: The SIP address you want Twilio to route your calls to. This must be a `sip:` schema. `sips` is NOT supported.
        :param friendly_name: A descriptive string that you create to describe the resource. It is not unique and can be up to 255 characters long.
        :param priority: The relative importance of the target. Can be an integer from 0 to 65535, inclusive, and the default is 10. The lowest number represents the most important target.
        :param weight: The value that determines the relative share of the load the Target should receive compared to other Targets with the same priority. Can be an integer from 1 to 65535, inclusive, and the default is 10. Targets with higher values receive more load than those with lower ones with the same priority.
        :param enabled: Whether the Target is enabled. The default is `true`.

        :returns: The created ConnectionPolicyTargetInstance
        """
        pass

    async def create_with_http_info_async(
        self,
        target: str,
        friendly_name: Union[str, object] = values.unset,
        priority: Union[int, object] = values.unset,
        weight: Union[int, object] = values.unset,
        enabled: Union[bool, object] = values.unset,
    ) -> ApiResponse:
        """
        Asynchronously create the ConnectionPolicyTargetInstance and return response metadata

        :param target: The SIP address you want Twilio to route your calls to. This must be a `sip:` schema. `sips` is NOT supported.
        :param friendly_name: A descriptive string that you create to describe the resource. It is not unique and can be up to 255 characters long.
        :param priority: The relative importance of the target. Can be an integer from 0 to 65535, inclusive, and the default is 10. The lowest number represents the most important target.
        :param weight: The value that determines the relative share of the load the Target should receive compared to other Targets with the same priority. Can be an integer from 1 to 65535, inclusive, and the default is 10. Targets with higher values receive more load than those with lower ones with the same priority.
        :param enabled: Whether the Target is enabled. The default is `true`.

        :returns: ApiResponse with instance, status code, and headers
        """
        pass

    def stream(
        self,
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> Iterator[ConnectionPolicyTargetInstance]:
        """
        Streams ConnectionPolicyTargetInstance records from the API as a generator stream.
        This operation lazily loads records as efficiently as possible until the limit
        is reached.
        The results are returned as a generator, so this operation is memory efficient.

        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: Generator that will yield up to limit results
        """
        pass

    async def stream_async(
        self,
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> AsyncIterator[ConnectionPolicyTargetInstance]:
        """
        Asynchronously streams ConnectionPolicyTargetInstance records from the API as a generator stream.
        This operation lazily loads records as efficiently as possible until the limit
        is reached.
        The results are returned as a generator, so this operation is memory efficient.

        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: Generator that will yield up to limit results
        """
        pass

    def stream_with_http_info(
        self,
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> tuple:
        """
        Streams ConnectionPolicyTargetInstance and returns headers from first page


        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: tuple of (generator, status_code, headers) where generator yields instances
        """
        pass

    async def stream_with_http_info_async(
        self,
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> tuple:
        """
        Asynchronously streams ConnectionPolicyTargetInstance and returns headers from first page


        :param limit: Upper limit for the number of records to return. stream()
                      guarantees to never return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, stream() will attempt to read the
                          limit with the most efficient page size, i.e. min(limit, 1000)

        :returns: tuple of (generator, status_code, headers) where generator yields instances
        """
        pass

    def list(
        self,
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> List[ConnectionPolicyTargetInstance]:
        """
        Lists ConnectionPolicyTargetInstance records from the API as a list.
        Unlike stream(), this operation is eager and will load `limit` records into
        memory before returning.

        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: list that will contain up to limit results
        """
        pass

    async def list_async(
        self,
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> List[ConnectionPolicyTargetInstance]:
        """
        Asynchronously lists ConnectionPolicyTargetInstance records from the API as a list.
        Unlike stream(), this operation is eager and will load `limit` records into
        memory before returning.

        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: list that will contain up to limit results
        """
        pass

    def list_with_http_info(
        self,
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Lists ConnectionPolicyTargetInstance and returns headers from first page


        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        pass

    async def list_with_http_info_async(
        self,
        limit: Optional[int] = None,
        page_size: Optional[int] = None,
    ) -> ApiResponse:
        """
        Asynchronously lists ConnectionPolicyTargetInstance and returns headers from first page


        :param limit: Upper limit for the number of records to return. list() guarantees
                      never to return more than limit.  Default is no limit
        :param page_size: Number of records to fetch per request, when not set will use
                          the default value of 50 records.  If no page_size is defined
                          but a limit is defined, list() will attempt to read the limit
                          with the most efficient page size, i.e. min(limit, 1000)

        :returns: ApiResponse with list of instances, status code, and headers
        """
        pass

    def page(
        self,
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ConnectionPolicyTargetPage:
        """
        Retrieve a single page of ConnectionPolicyTargetInstance records from the API.
        Request is executed immediately

        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of ConnectionPolicyTargetInstance
        """
        pass

    async def page_async(
        self,
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ConnectionPolicyTargetPage:
        """
        Asynchronously retrieve a single page of ConnectionPolicyTargetInstance records from the API.
        Request is executed immediately

        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: Page of ConnectionPolicyTargetInstance
        """
        pass

    def page_with_http_info(
        self,
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Retrieve a single page with response metadata


        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with ConnectionPolicyTargetPage, status code, and headers
        """
        pass

    async def page_with_http_info_async(
        self,
        page_token: Union[str, object] = values.unset,
        page_number: Union[int, object] = values.unset,
        page_size: Union[int, object] = values.unset,
    ) -> ApiResponse:
        """
        Asynchronously retrieve a single page with response metadata


        :param page_token: PageToken provided by the API
        :param page_number: Page Number, this value is simply for client state
        :param page_size: Number of records to return, defaults to 50

        :returns: ApiResponse with ConnectionPolicyTargetPage, status code, and headers
        """
        pass

    def get_page(self, target_url: str) -> ConnectionPolicyTargetPage:
        """
        Retrieve a specific page of ConnectionPolicyTargetInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of ConnectionPolicyTargetInstance
        """
        pass

    async def get_page_async(self, target_url: str) -> ConnectionPolicyTargetPage:
        """
        Asynchronously retrieve a specific page of ConnectionPolicyTargetInstance records from the API.
        Request is executed immediately

        :param target_url: API-generated URL for the requested results page

        :returns: Page of ConnectionPolicyTargetInstance
        """
        pass

    def get(self, sid: str) -> ConnectionPolicyTargetContext:
        """
        Constructs a ConnectionPolicyTargetContext

        :param sid: The unique string that we created to identify the Target resource to update.
        """
        pass

    def __call__(self, sid: str) -> ConnectionPolicyTargetContext:
        """
        Constructs a ConnectionPolicyTargetContext

        :param sid: The unique string that we created to identify the Target resource to update.
        """
        return ConnectionPolicyTargetContext(
            self._version,
            connection_policy_sid=self._solution["connection_policy_sid"],
            sid=sid,
        )

    def __repr__(self) -> str:
        """
        Provide a friendly representation

        :returns: Machine friendly representation
        """
        return "<Twilio.Voice.V1.ConnectionPolicyTargetList>"
